#!/bin/bash

# Minimal build script that relies on postinstall
set -e

echo "🚀 Minimal Vercel build"
echo "Environment: $VERCEL_ENV"
echo "NODE_ENV: $NODE_ENV"

# Just verify DATABASE_URL exists in production
if [ "$VERCEL_ENV" = "production" ] || [ "$NODE_ENV" = "production" ]; then
    if [ -z "$DATABASE_URL" ]; then
        echo "❌ ERROR: DATABASE_URL not set in production"
        exit 1
    fi
    echo "✅ DATABASE_URL configured for production"
fi

# Prisma client should already be generated by postinstall
echo "📋 Verifying Prisma client exists..."
if [ ! -d "node_modules/@prisma/client" ]; then
    echo "⚠️ Prisma client not found, generating..."
    npx prisma generate
fi

echo "🏗️ Building Next.js..."
npx next build

echo "✅ Build completed"